mlflow:
  experiment_name: news_experiments
  run_name: signlehead_bert-base-uncased_e10
  tracking_uri: mlruns

dataset: 
  news:
    root: ./data
    data_split: True # True: train, test | False: train, test, val
    data_path: news
    use_data_loader: True

model: 
  bert:
    model_name: bert-base-uncased #BioBERT-Basev1-0-PM #BioBERT-Basev1-0-PMC #BioBERT-Basev1-1 #BioBERT-Basev1-0-PM-PMC # bert-base-uncased
    freeze: False

training:
  type: singlehead_cls
  epoch : 10
  batch_size : 16
  use_cuda : True
  cv : True # False
  fold : 5

head: 
  single-head:
    heads: MultiLabelCLS

tokenizer:
  bert:
    name: bert_base_uncased 
    padding: max_length  
    truncation: True 
    max_length : 256

optimizer:
  adam:
    name: AdamW
    lr: 0.00002
