mlflow:
  experiment_name: twentynewsgroup_experiments
  run_name: signlehead_bert-base-uncased-e20
  tracking_uri: mlruns

dataset: 
  twentyNewsGroup:
    root: ./data
    data_split: True # True: train, test | False: train, test, val
    data_path: twentynewsgroup/twentynewsgroup_train.csv
    use_data_loader: True

model: 
  bert:
    model_name: bert-base-uncased
    freeze: False #True
    
training:
  # type: MTL_cls
  type: singlehead_cls
  epoch : 20
  batch_size : 16
  use_cuda : True
  # cv : True # False
  # fold : 5

head: 
  single-head:
    heads: MultiLabelCLS

tokenizer:
  bert:
    name: bert_base_uncased
    padding: max_length    # to pad to the longest sequence in the batch
    truncation: True  # truncate to a maximum length specified by the max_length
    max_length : 512

optimizer:
  adam:
    name: AdamW
    lr: 0.00002